### PR TITLE
Add missing icons in texts. Add missing tech/civic descriptions.

### PR DESCRIPTION
**Pull request by mrobaczyk**

### CODE REVIEW

**Comment by mrobaczyk** [comment]
I was wondering whether I should add unique improvements bonus yields to civic descriptions. Let me know, I will add to this PR.

**Comment by Apeul** [comment]
Hello, can you dm me on discord please ?

**Comment by gwillikers10** [comment]
Hello, thank you for your help.  I am going to incorporate these into my own commit.  One of my pending commits cleans up the formatting for all of the icon tags to be consistent and I want to fix the ones you are adding.

**Comment by mrobaczyk** [comment]
> Hello, thank you for your help. I am going to incorporate these into my own commit. One of my pending commits cleans up the formatting for all of the icon tags to be consistent and I want to fix the ones you are adding.

Ok thanks.

**Comment by gwillikers10** [comment]
The main reason I incorporated yours into mine instead of having Apeaul accept yours is that in one of my pending commits, I cleaned up most of the icon tags to be all caps as they were inconsistent.  The only ones I left not all caps are the multiword ones.  I didnt want to reintroduce lowercase ones from your commits.

**Comment by mrobaczyk** [comment]
> The main reason I incorporated yours into mine instead of having Apeaul accept yours is that in one of my pending commits, I cleaned up most of the icon tags to be all caps as they were inconsistent. The only ones I left not all caps are the multiword ones. I didnt want to reintroduce lowercase ones from your commits.

OK, no problem.

**Comment by mrobaczyk** [comment]
Changes incorporated into https://github.com/CivilizationVIBetterBalancedGame/BetterBalancedGame/pull/327

**Pull request closed without merging**
